import "../styles/globals.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import "macro-css";
import { setUserData } from "../redux/slices/user";
import { wrapper } from "../redux/store";
import { Api } from "../utils/api";
import { Provider } from "react-redux";
import { CssBaseline } from "@mui/material";

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>myPorto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="img/logomin.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <CssBaseline />

      <Component {...pageProps} />
    </>
  );
}

App.getInitialProps = wrapper.getInitialAppProps((store) => async ({ ctx, Component }) => {
  try {
    const userData = await Api(ctx).user.getMe();

    store.dispatch(setUserData(userData));
  } catch (error) {
    if (ctx.asPath === "/write") {
      ctx.res?.writeHead(302, { Location: "/403" });
      ctx.res?.end();
    }
    console.log(error);
  }
  return {
    pageProps: {
      ...(Component.getInitialProps ? await Component.getInitialProps({ ...ctx, store }) : {}),
    },
  };
});

export default wrapper.withRedux(App);
